# Generated by Django 4.2.11 on 2024-04-05 08:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('products', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
        ),
        migrations.AlterField(
            model_name='usercart',
            name='products',
            field=models.ManyToManyField(to='cart.productincart', verbose_name='Товары'),
        ),
    ]
